### ISSUE TITLE
Interstitial Guide Missing

### ISSUE THREAD

**Issue by sheyinn** [marius-bughiu/Plugin.AdMob#2]
Great plugin! Can't find the documentation on how to implement interstitial ads. It would be great to have those.

**Comment by marius-bughiu** [comment]
Hi @sheyinn, and thank you! I will update the readme soon, but in the meantime you can check the sample app. For interstitials you can use the `IInterstitialAdService` service, which exposes two methods for you:
- `PrepareAd` - this allows you to pre-load the add in the background, so that you can instantly show it to the user when the time is right
- `ShowAd` - shows the preloaded ad to the user

A full working example can be found here: https://github.com/marius-bughiu/Plugin.AdMob/blob/main/samples/Foo.Bar.SampleApp/MainPage.xaml.cs

**Comment by sheyinn** [comment]
Hello @marius-bughiu. Thanks for the guidance. I was able to get it to work.

**Comment by marius-bughiu** [comment]
Updated the readme with information on how to show interstitial ads. Closing.
